ComplianceControlDecorator: Convert to new action links interface
I was getting this error:

    ActionView::Template::Error (undefined method `split' for nil:NilClass
    Did you mean?  split_all):
        16:
        17:   / compliance controls without block
        18:   = render_compliance_control_block
        19:   = render_compliance_controls(@direct_compliance_controls)
        20:
        21:   / compliance controls with block
        22:   - if params[:q] && params[:q][:compliance_control_block_id_eq_any].try(:present?)
      app/helpers/table_builder_helper.rb:110:in `item_row_class_name'
      app/helpers/table_builder_helper.rb:290:in `tbody'
      app/helpers/table_builder_helper.rb:97:in `table_builder_2'
      app/helpers/compliance_control_sets_helper.rb:79:in `block in render_table_builder'
      app/helpers/compliance_control_sets_helper.rb:78:in `render_table_builder'
      app/helpers/compliance_control_sets_helper.rb:71:in `block (2 levels) in render_compliance_controls'
      app/helpers/compliance_control_sets_helper.rb:70:in `block in render_compliance_controls'
      app/helpers/compliance_control_sets_helper.rb:69:in `render_compliance_controls'
      app/views/compliance_control_sets/show.html.slim:19:in `_app_views_compliance_control_sets_show_html_slim___3528509151208629266_70279137561480'

The model name wasn't accessible from the view because this collection
is set up in an unorthodox way without a decorated collection.

Got help from Johan, and we ended up using the `model` param passed into
the table builder for this. It looks terrible with `model` all over the
place, but at least it gets us past the problem.

Refs #5586